### ISSUE TITLE
Feature request: Multiple instances

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Link#154]
I would like to see an "easy" way to create multiple instances of Prusa-Link so running these on an RPi3B+/4 or other powerful SBC like Odroid would be possible.

I have an Odroid-C2 and it is capable of running 4+ instances of Octoprint via USB.

**Comment by kubik369** [comment]
Ahoj Ondřeji (@ondratu),

how are those plans going, is this feature already supported? I am helping a friend set up a few (4-8 probably MK3S, not sure, bought them a few weeks back) Prusa printers and found this issue, so now I am unsure whether to use Octoprint or this new software of yours. I would like to use a single computer to control all of them through USB.

From the README, it seems that the program can be handed a specific serial device path and be opened on different ports, so I would assume you have already added this functionality. If no, from a glance, it seems that it should be possible to do this with docker or some other containerisation tool. Could you confirm either this or the fact that you already support it?

Thank you for your answer and ahoj zo Slovenska :)

**Comment by TojikCZ** [comment]
This is now a feature. Woo. Here's an RC, get the multi-instance image in Assets and try it out https://github.com/prusa3d/Prusa-Link/releases/tag/0.7.1rc1

**Comment by JuanGrados** [comment]
What's the difference regarding Multiinstance between 0.7.2 and 0.7.1.rc1 ?

I installed PrusaLink via pip install and 0.7.2 was the one installed. It has Miltiinstance but even though it "detects" the printers I  get a "500 - Internal Server Error" when I click on any of them at the Miltiintance web interface at port 8080.

Does have any of you had any success running multiple printers in Multiinstance mode?

Thanks!

**Comment by TojikCZ** [comment]
you might be missing ipcqueue from pip. also it needs root. There should not be almost any changes. Nobody reported anything except the known limitations

**Comment by JuanGrados** [comment]
Thanks for the tip, I'll gove it a try :)

**Comment by JuanGrados** [comment]
Hi, I checked and ipcqueue was already installed in the python virtual environment.
The error I get when clicking on one of the printers is:

```
Exception Traceback

Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8c76cdd0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/poorwsgi/wsgi.py", line 1135, in __request__
    args = self.handler_from_table(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/poorwsgi/wsgi.py", line 1074, in handler_from_table
    return handler(req, *req.path_args.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/web.py", line 178, in proxy
    response = pool_manager.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c76cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

  ```

Perhaps you spot what's wrong. Thanks for your time!

**Comment by JuanGrados** [comment]
More informations that could be  useful.

I noticed that prusalink-manager created three directotries, one per printer with names "PrusaLink1/2/3",
however  the directories are empty, no ini files or anything is created inside them.

When I run the clean command I get this error:

```
pi@raspberrypi:~/PrusaLink $ sudo  venv/bin/prusalink-manager clean
2023-10-16 10:23:45,109 WARNING {__main__.handle_process_stop():178} [ThreadPoolExecutor-0_0]: PrusaLink instance not running 
2023-10-16 10:23:45,111 WARNING {__main__.handle_process_stop():178} [ThreadPoolExecutor-0_0]: PrusaLink instance not running 
2023-10-16 10:23:45,113 WARNING {__main__.handle_process_stop():178} [ThreadPoolExecutor-0_2]: PrusaLink instance not running 
2023-10-16 10:24:00,126 WARNING {__main__.stop():98} [ThreadPoolExecutor-0_1]: Failed to stop - SIGKIL will be used! 
2023-10-16 10:24:00,236 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink1/prusalink.pid 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink1/prusalink.pid'
2023-10-16 10:24:00,238 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink1/power_panic 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink1/power_panic'
2023-10-16 10:24:00,239 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink1/threshold.data 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink1/threshold.data'
2023-10-16 10:24:00,244 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink2/prusalink.pid 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink2/prusalink.pid'
2023-10-16 10:24:00,246 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink2/power_panic 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink2/power_panic'
2023-10-16 10:24:00,247 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink2/threshold.data 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink2/threshold.data'
2023-10-16 10:24:00,248 ERROR {config_component.delete_folder():420} [MainThread]: Error deleting /home/pi/PrusaLink2/PrusaLink gcodes 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 417, in delete_folder
    shutil.rmtree(path)
  File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink2/PrusaLink gcodes'
2023-10-16 10:24:00,254 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink2/prusa_printer_settings.ini 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink2/prusa_printer_settings.ini'
2023-10-16 10:24:00,260 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink3/prusalink.pid 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink3/prusalink.pid'
2023-10-16 10:24:00,261 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink3/power_panic 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink3/power_panic'
2023-10-16 10:24:00,262 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink3/threshold.data 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink3/threshold.data'
2023-10-16 10:24:00,263 ERROR {config_component.delete_folder():420} [MainThread]: Error deleting /home/pi/PrusaLink3/PrusaLink gcodes 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 417, in delete_folder
    shutil.rmtree(path)
  File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink3/PrusaLink gcodes'
2023-10-16 10:24:00,265 ERROR {config_component.delete_file():411} [MainThread]: Error deleting /home/pi/PrusaLink3/prusa_printer_settings.ini 
Traceback (most recent call last):
  File "/home/pi/PrusaLink/venv/lib/python3.11/site-packages/prusa/link/multi_instance/config_component.py", line 408, in delete_file
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/PrusaLink3/prusa_printer_settings.ini'
```

**Comment by TojikCZ** [comment]
Okay, it's awesome you actually managed to get it working without the image. Yea, the cleaning errors are expected, just telling you the file was not there, it ignores it and goes on to the next

**Comment by JuanGrados** [comment]
One more question, is it possible to remove the requirement of authentication to access the instances of prusalink for each printer? I couldn't find where to disable it.

**Comment by TojikCZ** [comment]
Sorry there's not. I would like a centralized login for all the instances, but i don't know if I'll get to do that.
