### ISSUE TITLE
"No Internet access"

### ISSUE THREAD

**Issue by davidstosik** [prusa3d/Prusa-Link#728]
Hi there!
I just installed Prusa-Link on my Prusa i3 MK3S yesterday. I love it, this is such a great tool, I regret not hearing about it earlier!

It's been working fairly well overall. I managed to run a few prints through it, and can even monitor the print using a Pi Camera.

However, my printer has been emitting multiple beeps (similar to the menu navigation beeps), and rotating these messages on its display:

- `→No Internet access`
- `→Errors resolved`
- then  rotating between `→PrusaLink OK.` and the Pi's local IP

Simultaneously, I noticed the "PrusaConnect Status" info on PrusaLink Web's settings page would briefly switch to:

> DNS does not work, or there are other problems in communication to other hosts in the Internet. (https://connect.prusa3d.com)

then immediately back to:

> Successfully connected (https://connect.prusa3d.com)

Please note that I have no other network problems at home and the Pi Zero is one of the devices closest to the router (a few meters, separated by a couple drywalls).

This seems to have mostly no impact on my prints or even PrusaConnect's usability. (I might get a few seconds delay when displaying camera photos or telemetry, but that's about it.)

I think this is worth reporting though, maybe someone can help?

Not sure if this helps:

> ## Version
> 
> API: 0.9.0-legacy
> Hostname: prusa
> Firmware: 3.12.2-5713
> Server: 0.7.0rc3
> Text: PrusaLink 0.7.0rc3
> SDK: 0.7.0rc3
> Frontend: 3.12.0
> 
> ## System Version
> 
> Python: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
> Description: Raspbian GNU/Linux 11 (bullseye)
> RELEASE: 11
> CODENAME: bullseye
> ID: Raspbian

Update: oh, hey, here's something interesting in `daemon.log`:

```
	Apr 17 23:18:02 prusa prusa.link.web.lib.classes[520]: INFO: 192.168.0.168 - "GET /api/job HTTP/1.1" 200 422 {log_message():45}
	Apr 17 23:18:02 prusa prusa.link.web.lib.classes[520]: INFO: 192.168.0.168 - "GET /api/logs HTTP/1.1" 200 1083 {log_message():45}
👉🏻	Apr 17 23:18:03 prusa connect-printer[520]: ERROR: HTTPSConnectionPool(host='connect.prusa3d.com', port=443): Read timed out. (read timeout=10) {loop_step():742}
	Apr 17 23:18:03 prusa prusa.link.cameras.picamera_driver[520]: WARNING: Taking a photo! {take_a_photo():293}
	Apr 17 23:18:03 prusa prusa.link.web.lib.classes[520]: INFO: 192.168.0.168 - "GET /api/printer HTTP/1.1" 200 648 {log_message():45}
	Apr 17 23:18:03 prusa prusa.link.cameras.picamera_driver[520]: WARNING: Converting a photo {take_a_photo():312}
	Apr 17 23:18:03 prusa prusa.link.web.lib.classes[520]: INFO: 192.168.0.168 - "GET /api/job HTTP/1.1" 200 422 {log_message():45}
👉🏻	Apr 17 23:18:03 prusa camera_controller[520]: ERROR: Unexpected exception caught in SDK snapshot loop! {snapshot_loop():183}#012Traceback (most recent call last):#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request#012    six.raise_from(e, None)#012  File "<string>", line 3, in raise_from#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request#012    httplib_response = conn.getresponse()#012  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse#012    response.begin()#012  File "/usr/lib/python3.9/http/client.py", line 307, in begin#012    version, status, reason = self._read_status()#012  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status#012    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")#012  File "/usr/lib/python3.9/socket.py", line 704, in readinto#012    return self._sock.recv_into(b)#012  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into#012    return self.read(nbytes, buffer)#012  File "/usr/lib/python3.9/ssl.py", line 1099, in read#012    return self._sslobj.read(len, buffer)#012socket.timeout: The read operation timed out#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/home/jo/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send#012    resp = conn.urlopen(#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen#012    retries = retries.increment(#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment#012    raise six.reraise(type(error), error, _stacktrace)#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise#012    raise value#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen#012    httplib_response = self._make_request(#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request#012    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)#012  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout#012    raise ReadTimeoutError(#012urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='connect.prusa3d.com', port=443): Read timed out. (read timeout=10)#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/home/jo/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_controller.py", line 171, in snapshot_loop#012    res = item.send(self.session, self.server)#012  File "/home/jo/.local/lib/python3.9/site-packages/prusa/connect/printer/camera.py", line 58, in send#012    res = conn.request(method=self.method,#012  File "/home/jo/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/home/jo/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send#012    r = adapter.send(request, **kwargs)#012  File "/home/jo/.local/lib/python3.9/site-packages/requests/adapters.py", line 578, in send#012    raise ReadTimeout(e, request=request)#012requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='connect.prusa3d.com', port=443): Read timed out. (read timeout=10)
	Apr 17 23:18:03 prusa prusa.link.cameras.picamera_driver[520]: WARNING: Done converting a photo {take_a_photo():314}
```

Formatting the error (`s/#012/\n/`), I get this:
```
Apr 17 23:18:03 prusa camera_controller[520]: ERROR: Unexpected exception caught in SDK snapshot loop! {snapshot_loop():183}

Traceback (most recent call last):
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jo/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/jo/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='connect.prusa3d.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jo/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_controller.py", line 171, in snapshot_loop
    res = item.send(self.session, self.server)
  File "/home/jo/.local/lib/python3.9/site-packages/prusa/connect/printer/camera.py", line 58, in send
    res = conn.request(method=self.method,
  File "/home/jo/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jo/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/jo/.local/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='connect.prusa3d.com', port=443): Read timed out. (read timeout=10)
```

Is the photo upload taking too long and timing out? I've got a very good Internet connection, so I don't think the problem would be related to a slow upload speed on my end.

**Comment by ondratu** [comment]
Hi, yes, we have some problems on our backend, and probably, you found some another bug in Link - which means you got invalid error from link.

Good news is, that we found where is problem, and after some tests, it will be in production soon.

I left this issue opened to fix invalid error issue.

**Comment by gysnst2** [comment]
I would like to upvote this all of my printers are offline now

**Comment by wac-** [comment]
"`No internet access`" feels like a misleading error message for an API request timeout for PrusaConnect.
Maybe "`PrusaConnect error`" for this kind of error, since that will still fit on the screen.

**Comment by czesiu20** [comment]
I have similar problem. I'm losing connection to PrusaLink.
The solution for me is to check the option "Unlink camera from CONNECT" in the page Cameras.
I also noticed that my RPI ZERO 2W is extremely hot.
I'm using:
Firmware: 3.13.1-6876
Server: 0.7.1rc1
Text: PrusaLink 0.7.1rc1
SDK: 0.7.1rc1
Frontend: 3.12.0
and RPI Camera v2
