### ISSUE TITLE
python 3.13 incompatability

### ISSUE THREAD

**Issue by ausil** [prusa3d/Prusa-Link#991]
According to https://docs.python.org/3.13/whatsnew/3.13.html

PEP 594: Remove the cgi and cgitb modules, deprecated in Python 3.11.

```
Traceback (most recent call last):
  File "/home/dennis/.local/bin/prusalink", line 5, in <module>
    from prusa.link.__main__ import main
  File "/home/dennis/.local/lib/python3.13/site-packages/prusa/link/__main__.py", line 29, in <module>
    from .daemon import Daemon  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennis/.local/lib/python3.13/site-packages/prusa/link/daemon.py", line 10, in <module>
    from .printer_adapter import prusa_link
  File "/home/dennis/.local/lib/python3.13/site-packages/prusa/link/printer_adapter/prusa_link.py", line 26, in <module>
    from ..conditions import HW, ROOT_COND, UPGRADED, use_connect_errors
  File "/home/dennis/.local/lib/python3.13/site-packages/prusa/link/conditions.py", line 8, in <module>
    from poorwsgi import state
  File "/home/dennis/.local/lib/python3.13/site-packages/poorwsgi/__init__.py", line 24, in <module>
    from poorwsgi.wsgi import Application
  File "/home/dennis/.local/lib/python3.13/site-packages/poorwsgi/wsgi.py", line 24, in <module>
    from poorwsgi.request import Request, SimpleRequest
  File "/home/dennis/.local/lib/python3.13/site-packages/poorwsgi/request.py", line 9, in <module>
    from cgi import FieldStorage as CgiFieldStorage, parse_header
ModuleNotFoundError: No module named 'cgi'


```

**Comment by ausil** [comment]
I filed an issue in poorwsgi also https://github.com/PoorHttp/PoorWSGI/issues/36
